### ISSUE TITLE
Add first contrib

### ISSUE THREAD

**Issue by Eagle-X-9** [Eagle-X-9/Learnify-Pro#1]
1. Setting up of code base in stage branch (push the code)
2. Next use dev01 branch for contribution 
3. Stage is the testing branch 
4. Every Dev branch will go through the stage branch
5. Once the Stage is running fine Merge it to main branch

**Comment by jaki729** [comment]
Joined in @Eagle-X-9

**Comment by BinaryBuilderPR** [comment]
Completed the initial frontend Project setup

**Comment by Eagle-X-9** [comment]
Great to see the contribution @BinaryBuilderPR
